_wandb:
    value:
        cli_version: 0.21.1
        e:
            avqy8zm6ozt6vk0l0k1a35bupx5fixqe:
                codePath: log_data.py
                codePathLocal: log_data.py
                email: bensharn@gmail.com
                executable: /Users/benjamingoodwin/ml_ops_final/comp_4705_final_project/venv/bin/python3
                git:
                    remote: https://github.com/bgoodwin143/comp_4705_final_project.git
                host: Benjamins-MacBook-Pro-5.local
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/benjamingoodwin/ml_ops_final/comp_4705_final_project/log_data.py
                python: CPython 3.12.8
                root: /Users/benjamingoodwin/ml_ops_final/comp_4705_final_project
                startedAt: "2025-08-13T20:05:12.386543Z"
                writerId: avqy8zm6ozt6vk0l0k1a35bupx5fixqe
        m: []
        python_version: 3.12.8
        t:
            "3":
                - 2
            "4": 3.12.8
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
